### ISSUE TITLE
hts/tabix: move ErrNoReference et al out of internal

### ISSUE THREAD

**Issue by brentp** [biogo/hts#16]
I want to check for ErroNoReference but can't do so in go 1.5 because it is in "internal". I can make a PR to move it if you have a suggestion where.

**Comment by kortschak** [comment]
In the case where you are using that, you can just check against nil, the worst that happens is you get the same invalid work done twice.

The alternative is to have both tabix and csi check for identity with ErrNoReference and replace it with their own version, or make another package purely for that error value (it doesn't fit in bgzf/index because that package has no notion of a reference).

**Comment by kortschak** [comment]
I've had a further look and I'll move it. There are a few other things to do there, so I'll send the PR.
