### ISSUE TITLE
CSI Magic Number

### ISSUE THREAD

**Issue by nathanhaigh** [biogo/hts#73]
I've been having a look at the CSI specs and your code. Shouldn't the magic number for CSI be:

    var csiMagic = [4]byte{'C', 'S', 'I', 0x1}

instead of:

    var csiMagic = [3]byte{'C', 'S', 'I'}

Here: https://github.com/biogo/hts/blob/master/csi/csi.go#L16

**Comment by kortschak** [comment]
The CSI magic number is version-dependent. CSIv1 is "CSI\x01", CSIv2 is "CSI\x02". The number is [written out programmatically](https://github.com/biogo/hts/blob/master/csi/csi_write.go#L21-L28) rather than from a constant, and [read similarly](https://github.com/biogo/hts/blob/master/csi/csi_read.go#L27-L42).
