### ISSUE TITLE
I'm not sure if the record.End() returns thre right position.

### ISSUE THREAD

**Issue by dongweigogo** [biogo/hts#84]
for example, a record from a sam file:
ST-E00205:338:HJMLJALXX:3:1116:29000:35942      161     6       97894792        60      150M    =       97894892       250     TGAACTACTCTTCACTTGAGAACTAGAATTTCATTATTTCTTCTTTATTCTCAGTCTTCATTAGTTTTTATCTTTTCAGCAACATTTGAAACAACAGAACACACCCTCCCTCCTTTTTGAAATATTGTCTTTATTTTTAGGACACCACTG  AAAFFJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFFJJJJJJJJJJJJJJJJJJJJJJJJFJJAFJFJJJJAAAJJJJJJJJ7-<FFJ<JFJFJJ7JJJJJJA<AFFJJ<FFJFFJJFFJJFFFFAFJF<AFJ  NM:i:0  MD:Z:150       AS:i:150 XS:i:0  RG:Z:bwa

some output by using the hts package:
Rec Start from record.Start():  97894791
Rec End from record.End():  97894941    //here, 97894940 or 97894941?
Rec Len from record.Len():  150

The sequencing strategy is paired-end 150. Thus, I just think the end position of record should be 97894940, then the record length is 97894940-97894791+1=150. Otherwise, if the end position was 97894941, the length would be 97894941-97894791+1=151. 

Might I be right?

**Comment by kortschak** [comment]
The coordinate system used in all bíogo packages is zero-based half open (except for cases where there is writing out in formats that demand one-based like SAM and GFF). This is because zero-based half open allows easier arithmetic, matches slicing notation and is not brain dead (one-based coordinates preclude useful things like zero-length features).

So this is as expected (note that the `Len` method calculates based on the `End` return).

**Comment by dongweigogo** [comment]
Well, that make senses. Thanks.
